version: '3.0'

services:
  frontend:
    image: sez54321/mse_2024_sezen_fe
    environment:
      - APP_ENV_PREFIX=VITE_
      - VITE_FORUM_BACKEND_SERVER=http://localhost:8080
    container_name: frontend
    ports:
      - "8079:8079"
  backend:
    image: sez54321/mse_2024_sezen_be
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: